name: flutter_bluetooth_serial
version: 0.4.1
description: A basic Flutter Bluetooth Serial library with improved Android 12+ support
homepage: https://github.com/develeps/flutter_bluetooth_serial
repository: https://github.com/develeps/flutter_bluetooth_serial
issue_tracker: https://github.com/develeps/flutter_bluetooth_serial/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.github.develeps.flutterbluetoothserial
        pluginClass: FlutterBluetoothSerialPlugin
